### ISSUE TITLE
想問一下有辦法在mac 運行嗎

### ISSUE THREAD

**Issue by sky456757** [Zhen-Bo/Auto-FGO#1]
測了一下好像在調用adb的時候會出問題

**Comment by Zhen-Bo** [comment]
> 測了一下好像在調用adb的時候會出問題

請自行GOOGLE MAC電腦ADB的裝法,然後把start.py第27,28行刪掉,改成os.system("adb start-server")

**Comment by sky456757** [comment]
@Zhen-Bo 感謝，趕快搞定過幾天就可以刷箱了
