### ISSUE TITLE
使用疑問

### ISSUE THREAD

**Issue by sky456757** [Zhen-Bo/Auto-FGO#2]
請問腳本要在遊戲的哪個畫面開始執行，還有抽箱功能怎麼使用，感謝

**Comment by Zhen-Bo** [comment]
把你要進的關卡放在選單最上面就能用建議你去參考我第[2次重的腳本](https://github.com/Zhen-Bo/Fgo-Script)的文件或是直接用這版本,,這個專案只是單純我上傳來版本控管用
至於抽箱功能在啟動的時候要加入參數
